### ISSUE TITLE
All OPTIONS Requests are not sending Auth Basic credentials

### ISSUE THREAD

**Issue by jkroepke** [aarnaud/lxd-webui#17]
Hi!

I'm using nginx as proxy for lxd api. nginx is configured via to request credentials via auth basic and using ssl client certifcate to authentifcate agist lxd api.

The lxd web gui is working fine in the setup, expect I can't open the console. It looks like, the AJAX to the exec endpoint is send without credentials, like if I disbale Send XHRs with credentials in the settings tab.

Can you check, if the OPTIONS request is send with credentials?

**Comment by aarnaud** [comment]
Hi, 

How had you fix this issue? The web terminal used websocket request, maybe your Nginx configuration don't accept websocket.

**Comment by jkroepke** [comment]
Browser start a CORS preflight request to gain some informations about the CORS headers. The OPTION request is not from your app, The request is from the browser itself and does not support authentication. Thats why I'm close the issue.

I found the on google and it works well: http://serverfault.com/questions/698559/disable-authentication-for-http-options-method-preflight-request-in-nginx. This bypass the authentifcation and does only returm the requested CORS headers.

Websockets working fine in nginx.

**Comment by aarnaud** [comment]
Thanks for this details
