### ISSUE TITLE
_lxdServerUrl=https://127.0.0.1:8443

### ISSUE THREAD

**Issue by whbackus** [aarnaud/lxd-webui#20]
Hi, 
problem:  home page is blocked because the LXD URL is fixed at 127.0.0.1:8443
the _lxdServerUrl variable value is hard coded in main.9fbca5763aafa5565dad.bundle.js file.
![github](https://user-images.githubusercontent.com/33870851/33078884-4e8ffe14-ced4-11e7-8b1e-30323dd689bc.jpg)
**How to resolve:**
edit main.9fbca5763aafa5565dad.bundle.js and change 127.0.0.1 with the LXD IP address istance.
( LXD must be accessible from your client **[WARNING possible security issue.]**)

**Comment by aarnaud** [comment]
Hi, thanks for your feedback

It's not a bug, neither a security issue.

By default it's 127.0.0.1 but you can change the url in the config or in your browsers

```
// Get LXD Server URL in localstorage
        let lxdServerUrl = localStorage.getItem('lxd_server_url');
        // If LXD Server URL not found, set default URL to localhost
        if (!lxdServerUrl) {
            this._lxdServerUrl = 'https://127.0.0.1:8443';
        } else {
            this._lxdServerUrl = lxdServerUrl;
}
```

I persist your value in browser in local Storage

**Comment by aarnaud** [comment]
It's possible load a config file, but it's not implemented
